const Storage={prefix:'dashboard_',get(k,f=null){try{const i=localStorage.getItem(this.prefix+k);return i?JSON.parse(i):f}catch{return f}},set(k,v){try{localStorage.setItem(this.prefix+k,JSON.stringify(v))}catch(e){}},remove(k){try{localStorage.removeItem(this.prefix+k)}catch{}}};
const U={pad(n){return n<10?'0'+n:n},formatDate(d){const w=['星期日','星期一','星期二','星期三','星期四','星期五','星期六'];return`${d.getFullYear()}年${this.pad(d.getMonth()+1)}月${this.pad(d.getDate())}日 ${w[d.getDay()]}`},formatTime(d){return`${this.pad(d.getHours())}:${this.pad(d.getMinutes())}:${this.pad(d.getSeconds())}`},getToday(){return new Date().toISOString().slice(0,10)},debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}},throttle(fn,ms){let l=0;return(...a)=>{const n=Date.now();if(n-l>=ms){l=n;fn(...a)}}}};

/* ====== Router ====== */
const Router={init(){document.querySelectorAll('.nav-item[data-view]').forEach(i=>{i.addEventListener('click',e=>{e.preventDefault();this.go(i.dataset.view)})});document.querySelectorAll('.quick-item[data-view]').forEach(i=>{i.addEventListener('click',()=>this.go(i.dataset.view))})},go(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));const t=document.getElementById(`view-${v}`);if(t)t.classList.add('active');const n=document.querySelector(`.nav-item[data-view="${v}"]`);if(n)n.classList.add('active');document.getElementById('sidebar')?.classList.remove('mobile-open');if(v==='stats')setTimeout(updateCharts,100)}};

/* ====== Clock ====== */
const Clock={init(){this.upd();setInterval(()=>this.upd(),1000)},upd(){const n=new Date();const c=document.getElementById('topbar-clock');if(c)c.textContent=U.formatTime(n);const d=document.getElementById('greeting-date');if(d)d.textContent=U.formatDate(n);this.greet(n)},greet(n){const h=n.getHours(),e=document.getElementById('greeting-text');if(!e)return;let g;if(h<11)g='早上好，新的一天开始了！';else if(h<13)g='中午好，注意休息。';else if(h<18)g='下午好，继续保持专注！';else g='晚上好，辛苦了一天。';e.textContent=g}};

/* ====== Weather ====== */
const Weather={async init(){const c=Storage.get('weather');if(c&&c.ts&&Date.now()-c.ts<30e5){this.render(c.d);return}await this.loc()},async loc(){if(!navigator.geolocation){this.showManual();return}navigator.geolocation.getCurrentPosition(async p=>await this.fetch(p.coords.latitude,p.coords.longitude),()=>{this.showManual()})},async fetch(lat,lon){try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m,uv_index&timezone=auto`);if(!r.ok)throw 0;const d=await r.json();const f=this.fmt(d);Storage.set('weather',{ts:Date.now(),d:f});this.render(f);document.getElementById('city-search')?.style.setProperty('display','none')}catch{this.showManual()}},fmt(a){const c=a.current;return{temp:Math.round(c.temperature_2m),feels:Math.round(c.apparent_temperature),hum:c.relative_humidity_2m,wind:Math.round(c.wind_speed_10m),uv:Math.round((c.uv_index||0)*10)/10,icon:this.icon(c.weather_code),desc:this.desc(c.weather_code)}},icon(c){if(c===0)return'\u2600\uFE0F';if(c<=3)return'\u26C5';if(c<=48)return'\ud83c\udf2b\uFE0F';if(c<=67)return'\ud83c\udf27\uFE0F';if(c<=86)return'\ud83c\udf28\uFE0F';return'\u26C5'},desc(c){if(c===0)return'\u6674\u6717';if(c<=3)return'\u591A\u4E91';if(c<=48)return'\u96FE';if(c<=67)return'\u4E0B\u96E8';if(c<=86)return'\u5927\u96EA';return'\u591A\u4E91'},render(d){const c=document.getElementById('weather-content');if(!c)return;c.innerHTML=`<div class="weather-main"><span class="weather-icon">${d.icon}</span><span class="weather-temp">${d.temp}°C</span></div><div class="weather-details"><div>\ud83c\udf21\uFE0F \u4F53\u611F ${d.feels}°C</div><div>\ud83d\udca7 \u6E7F\u5EA6 ${d.hum}%</div><div>\ud83d\udca8 \u98CE\u901F ${d.wind} km/h</div><div>\u2600\uFE0F UV ${d.uv}</div><div>\ud83c\udf24\uFE0F ${d.desc}</div></div>`;const w=document.getElementById('topbar-weather-icon');if(w)w.textContent=d.icon;const wt=document.getElementById('topbar-weather-temp');if(wt)wt.textContent=`${d.temp}°`},showManual(){const e=document.getElementById('city-search');if(e){e.style.setProperty('display','flex');const b=document.getElementById('city-search-btn');const inp=document.getElementById('city-input');b?.addEventListener('click',async()=>{const city=inp.value.trim();if(!city)return;try{const g=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1`);const gd=await g.json();if(!gd.results?.length){alert('\u672A\u627E\u5230\u57CE\u5E02');return}const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${gd.results[0].latitude}&longitude=${gd.results[0].longitude}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m,uv_index&timezone=auto`);const d=await r.json();const f=this.fmt(d);Storage.set('weather',{ts:Date.now(),d:f});this.render(f);e.style.setProperty('display','none')}catch{alert('\u83B7\u53D6\u5931\u8D25')}})}}};

/* ====== Quotes ====== */
const Quotes={local:['\u4F60\u4ECA\u5929\u7684\u52AA\u529B\uFF0C\u662F\u672A\u6765\u6700\u597D\u7684\u793C\u7269\u3002','\u5148\u5B8C\u6210\uFF0C\u518D\u5B8C\u7F8E\u3002','\u4E13\u6CE8\u662F\u4E00\u79CD\u7A00\u7F3A\u80FD\u529B\u3002','\u65F6\u95F4\u82B1\u5728\u54EA\u91CC\uFF0C\u4EBA\u751F\u5C31\u5728\u54EA\u91CC\u3002','\u6BCF\u5929\u8FDB\u6B65\u4E00\u70B9\u70B9\uFF0C\u7EC8\u4F1A\u6210\u5C31\u5927\u6211\u3002','\u81EA\u5F8B\u7ED9\u6211\u81EA\u7531\u3002','\u4E0D\u79EF\u78AF\u6B65\uFF0C\u65E0\u4EE5\u81F3\u5343\u91CC\u3002'],async init(){this.render();document.getElementById('refresh-quote')?.addEventListener('click',()=>this.render())},async render(){const e=document.getElementById('greeting-quote');if(!e)return;try{const r=await fetch('https://apiquot.es/api/v1/quotes/random?length=short');if(r.ok){const d=await r.json();if(d.results?.length){e.innerHTML=`<span class="quote-text">\u2728 ${d.results[0].text}</span><button class="refresh-btn" id="refresh-quote">\u21BB</button>`;return}}}catch{}const q=this.local[Math.floor(Math.random()*this.local.length)];e.innerHTML=`<span class="quote-text">\u2728 ${q}</span><button class="refresh-btn" id="refresh-quote">\u21BB</button>`}};

/* ====== Todo ====== */
const Todo={items:[],todayKey:'',init(){this.items=Storage.get('todos',[]);this.todayKey=U.getToday();this.render()},add(t){t=t.trim();if(!t)return;this.items.push({id:Date.now(),text:t,done:false,date:this.todayKey,order:this.today.filter(i=>i.date===this.todayKey).length});this.save();this.render()},toggle(id){const i=this.items.find(x=>x.id===id);if(i){i.done=!i.done;this.save();this.render()}},del(id){this.items=this.items.filter(x=>x.id!==id);this.save();this.render()},move(id,dir){const t=this.today,tI=t.findIndex(x=>x.id===id);const nI=tI+dir;if(nI<0||nI>=t.length)return;[t[tI].order,t[nI].order]=[t[nI].order,t[tI].order];this.save();this.render()},today(){return this.items.filter(i=>i.date===this.todayKey)},save(){this.items.sort((a,b)=>a.order-b.order);Storage.set('todos',this.items)},render(){const list=document.getElementById('todo-list');if(!list)return;const items=this.today(),dc=items.filter(i=>i.done).length;const tot=items.length,pct=tot?Math.round((dc/tot)*100):0;[`todo-count`,`todo-count-2`].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=`${dc}/${tot}`});[`todo-percent`,`todo-percent-2`].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=`${pct}%`});if(!items.length){list.innerHTML='<div style="text-align:center;color:var(--text-secondary);padding:20px">\u6682\u65E0\u4EFB\u52A1\uFF0C\u6DFB\u52A0\u4E00\u4E2A\u5427\uFF01</div>';return}list.innerHTML=items.map(i=>`<div class="todo-item ${i.done?'done':''}" data-id="${i.id}"><div class="todo-checkbox"></div><span class="todo-label">${i.text}</span><div class="todo-actions"><button data-mu>\u25B2</button><button data-md>\u25BC</button><button data-del>\u2716</button></div></div>`).join('');this.bindEvents(list)},bindEvents(l){l.querySelectorAll('.todo-checkbox').forEach(c=>{const id=+c.parentElement.dataset.id;c.addEventListener('click',()=>this.toggle(id)});l.querySelectorAll('[data-del]').forEach(b=>{const id=+b.closest('.todo-item').dataset.id;b.addEventListener('click',()=>this.del(id)});l.querySelectorAll('[data-mu]').forEach(b=>{const id=+b.closest('.todo-item').dataset.id;b.addEventListener('click',()=>this.move(id,-1)});l.querySelectorAll('[data-md]').forEach(b=>{const id=+b.closest('.todo-item').dataset.id;b.addEventListener('click',()=>this.move(id,1))})},initInput(inputId,btnId,view){const inp=document.getElementById(inputId);const btn=document.getElementById(btnId);const h=()=>{this.add(inp.value);inp.value=''};btn?.addEventListener('click',h);inp?.addEventListener('keypress',e=>{if(e.key==='Enter')h()})}};

/* ====== Stats ====== */
const Stats={get w(){return Storage.get(`w_${U.getToday()}`,0)},set w(v){Storage.set(`w_${U.getToday()}`,v)},get s(){return Storage.get(`s_${U.getToday()}`,0)},set s(v){Storage.set(`s_${U.getToday()}`,v)},get f(){return Storage.get(`f_${U.getToday()}`,0)},set f(v){Storage.set(`f_${U.getToday()}`,v)},get sl(){return Storage.get(`sl_${U.getToday()}`,0)},set sl(v){Storage.set(`sl_${U.getToday()}`,v)},addWater(a){this.w=(this.w||0)+a;this.upd()},addSteps(){const i=document.getElementById('steps-input');const v=+i.value;if(v>0){this.s=v;i.value='';this.upd()}},addSleep(){const i=document.getElementById('sleep-input');const v=i.value;if(!v)return;const[h,m]=v.split(':').map(Number);this.sl=h*60+m;this.upd()},resetAll(){this.w=0;this.s=0;this.sl=0;this.upd()},upd(){const wEl=document.getElementById('water-value'),wB=document.getElementById('water-progress');if(wEl)wEl.textContent=`${(this.w||0).toLocaleString()} ML`;if(wB)wB.style.width=`${Math.min(100,(this.w||0)/20)}%`;const sEl=document.getElementById('steps-value'),sB=document.getElementById('steps-progress');if(sEl)sEl.textContent=(this.s||0).toLocaleString();if(sB)sB.style.width=`${Math.min(100,(this.s||0)/100)}%`;const fEl=document.getElementById('focus-value'),fB=document.getElementById('focus-progress');if(fEl)fEl.textContent=`${Math.floor((this.f||0)/60)}h ${(this.f||0)%60}m`;if(fB)fB.style.width=`${Math.min(100,(this.f||0)/8)}%`;const slEl=document.getElementById('sleep-value'),slB=document.getElementById('sleep-progress');const slH=Math.floor((this.sl||0)/60),slM=(this.sl||0)%60;if(slEl)slEl.textContent=`${slH}h ${slM}m`;if(slB)slB.style.width=`${Math.min(100,(this.sl||0)/8)}%`;updateCharts()},init(){document.querySelectorAll('[data-action]').forEach(b=>{b.addEventListener('click',()=>{const a=b.dataset.action;const am=b.dataset.amount;if(a==='add-water')this.addWater(+am);else if(a==='reset-water')this.w=0;else if(a==='add-steps')this.addSteps();else if(a==='reset-steps')this.s=0;else if(a==='add-sleep')this.addSleep();else if(a==='reset-sleep')this.sl=0;this.upd()});});const si=document.getElementById('steps-input');si?.addEventListener('keypress',e=>{if(e.key==='Enter')this.addSteps()});const sl=document.getElementById('sleep-input');sl?.addEventListener('change',()=>this.addSleep());this.upd()}};

/* ====== Pomodoro ====== */
const Pomo={timer:null,state:'idle',timeLeft:0,isFocus:true,init(){this.focusM=Storage.get('pf',25);this.breakM=Storage.get('pb',5);const fi=document.getElementById('pomo-focus');const bi=document.getElementById('pomo-break');if(fi)fi.value=this.focusM;if(bi)bi.value=this.breakM;fi?.addEventListener('change',e=>{this.focusM=+e.target.value;Storage.set('pf',this.focusM)});bi?.addEventListener('change',e=>{this.breakM=+e.target.value;Storage.set('pb',this.breakM)});document.getElementById('start-pomo')?.addEventListener('click',()=>this.start());document.getElementById('pause-pomo')?.addEventListener('click',()=>this.pause());document.getElementById('reset-pomo')?.addEventListener('click',()=>this.reset());this.upd()},start(){if(this.state==='idle')this.timeLeft=(this.isFocus?this.focusM:this.breakM)*60;this.state='running';document.getElementById('start-pomo').disabled=true;document.getElementById('pause-pomo').disabled=false;this.timer=setInterval(()=>{this.timeLeft--;this.upd();if(this.timeLeft<=0)this.complete()},1000)},pause(){this.state='paused';clearInterval(this.timer);document.getElementById('start-pomo').disabled=false;document.getElementById('pause-pomo').disabled=true},reset(){this.state='idle';clearInterval(this.timer);this.timeLeft=0;this.upd();document.getElementById('timer-label').textContent='\u51C6\u5907\u5F00\u59CB';document.getElementById('start-pomo').disabled=false;document.getElementById('pause-pomo').disabled=true},complete(){clearInterval(this.timer);this.state='idle';if(this.isFocus){let c=Storage.get('pomo_count',0)+1;Storage.set('pomo_count',c);document.getElementById('pomo-count').textContent=c;Stats.f=(Stats.f||0)+this.focusM;Stats.upd();this.isFocus=false;this.timeLeft=this.breakM*60;document.getElementById('timer-label').textContent='\u4F11\u606F\u65F6\u95F4\uFF01';this.notify('\u6A5F\u829D\u69B3\u5B8C\u6210\uFF01','\u4F11\u606F 5 \u5206\u949F\u5427')}else{this.isFocus=true;this.timeLeft=this.focusM*60;document.getElementById('timer-label').textContent='\u4E13\u6CE8\u65F6\u95F4\uFF01';this.notify('\u4F11\u6069\u7ED3\u675F\uFF01','\u5F00\u59CB\u65B0\u7684\u4E13\u6CE8')}this.play();this.upd()},upd(){const m=Math.floor(this.timeLeft/60),s=this.timeLeft%60;const d=document.getElementById('timer-display');if(d)d.textContent=`${U.pad(m)}:${U.pad(s)}`,document.title=`${U.pad(m)}:${U.pad(s)} - Dashboard`},notify(t,b){if('Notification'in window&&Notification.permission==='granted')new Notification(t,{body:b})},play(){try{const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=800;g.gain.value=0.3;o.start();o.stop(c.currentTime+0.5)}catch{}}};

/* ====== Notebook ====== */
const Notes={notes:[],activeId:null,init(){this.notes=Storage.get('notes',[]);this.bind();this.renderList();if(this.notes.length)this.select(this.notes[0].id)},bind(){document.getElementById('new-note')?.addEventListener('click',()=>this.create());document.getElementById('save-note')?.addEventListener('click',()=>this.save());document.getElementById('delete-note')?.addEventListener('click',()=>this.del());document.getElementById('note-search')?.addEventListener('input',U.debounce(e=>this.renderList(e.target.value),300));document.querySelectorAll('.note-tab').forEach(t=>{t.addEventListener('click',()=>this.switchTab(t.dataset.tab))})},create(){const n={id:Date.now(),title:'\u65E0\u6807\u9898',content:'',created:Date.now()};this.notes.unshift(n);this.persist();this.renderList();this.select(n.id)},select(id){this.activeId=id;const n=this.notes.find(x=>x.id===id);if(!n)return;const ti=document.getElementById('note-title'),co=document.getElementById('note-content');if(ti)ti.value=n.title;if(co)co.value=n.content;this.renderList()},save(){if(!this.activeId)return;const n=this.notes.find(x=>x.id===this.activeId);if(!n)return;n.title=document.getElementById('note-title')?.value||'\u65E0\u6807\u9898';n.content=document.getElementById('note-content')?.value||'';n.updated=Date.now();this.persist();this.renderList()},persist(){Storage.set('notes',this.notes)},del(){if(!this.activeId)return;this.notes=this.notes.filter(x=>x.id!==this.activeId);this.persist();this.activeId=this.notes.length?this.notes[0].id:null;if(this.activeId)this.select(this.activeId);else{const t=document.getElementById('note-title'),c=document.getElementById('note-content');if(t)t.value='';if(c)c.value=''}this.renderList()},renderList(f){const l=document.getElementById('note-list');if(!l)return;const fl=f?this.notes.filter(n=>n.title.toLowerCase().includes(f.toLowerCase())||n.content.toLowerCase().includes(f.toLowerCase())):this.notes;l.innerHTML=fl.map(n=>`<div class="note-item ${n.id===this.activeId?'active':''}" data-id="${n.id}">${n.title||'\u65E0\u6807\u9898'}</div>`).join('');l.querySelectorAll('.note-item').forEach(e=>{e.addEventListener('click',()=>this.select(+e.dataset.id))})},switchTab(tab){document.querySelectorAll('.note-tab').forEach(t=>t.classList.remove('active'));document.querySelector(`.note-tab[data-tab="${tab}"]`)?.classList.add('active');const ta=document.getElementById('note-content'),pv=document.getElementById('note-preview');if(tab==='edit'){ta.style.display='block';pv.classList.remove('visible')}else{ta.style.display='none';pv.innerHTML=marked.parse(ta?.value||'');pv.classList.add('visible')}}};

/* ====== Calendar ====== */const Calendar={cur:new Date(),events:[],selDate:null,init(){this.events=Storage.get('cal_ev',[]);this.render()},bind(){document.getElementById('prev-month')?.addEventListener('click',()=>{this.cur.setMonth(this.cur.getMonth()-1);this.render()});document.getElementById('next-month')?.addEventListener('click',()=>{this.cur.setMonth(this.cur.getMonth()+1);this.render()});document.getElementById('add-event')?.addEventListener('click',()=>this.addEv())},render(){const g=document.getElementById('calendar-grid'),my=document.getElementById('calendar-month-year');if(!g||!my)return;const y=this.cur.getFullYear(),m=this.cur.getMonth();my.textContent=`${y}年${m+1}月`;const today=U.getToday();const first=new Date(y,m,1),last=new Date(y,m+1,0),sd=first.getDay(),days=[];for(let i=sd-1;i>=0;i--){const d=new Date(y,m,-i);days.push({d:i,m:d.getMonth(),y:d.getFullYear(),other:true})}for(let i=1;i<=last.getDate();i++){days.push({d:i,m,y,other:false})}const rem=42-days.length;for(let i=1;i<=rem;i++){const d=new Date(y,m+1,i);days.push({d:i,m:d.getMonth(),y:d.getFullYear(),other:true})}g.innerHTML=days.map(d=>{const k=`${d.y}-${U.pad(d.m+1)}-${U.pad(d.d)}`;const isT=k===today;const hasE=this.events.some(e=>e.date===k);return`<div class="calendar-day ${d.other?'other-month':''} ${isT?'today':''} ${hasE?'has-event':''}" data-date="${k}">${d.d}</div>`}).join('');g.querySelectorAll('.calendar-day:not(.other-month)').forEach(e=>{e.addEventListener('click',()=>this.sel(e.dataset.date))})},sel(d){this.selDate=d;document.getElementById('event-area').style.setProperty('display','block');document.getElementById('selected-date').textContent=d;this.renderEv()},addEv(){if(!this.selDate)return;const i=document.getElementById('event-input');const t=i?.value?.trim();if(!t)return;this.events.push({id:Date.now(),date:this.selDate,text:t});Storage.set('cal_ev',this.events);i.value='';this.render();this.renderEv()},renderEv(){const l=document.getElementById('event-list');if(!l)return;const de=this.events.filter(e=>e.date===this.selDate);l.innerHTML=de.map(e=>`<div class="event-item"><span>${e.text}</span><button data-id="${e.id}">\u2716</button></div>`).join('');l.querySelectorAll('button').forEach(b=>{b.addEventListener('click',()=>{this.events=this.events.filter(e=>e.id!==+b.dataset.id);Storage.set('cal_ev',this.events);this.render();this.renderEv()})})}};

/* ====== Inspiration ====== */const Insp={tips:[{t:'\u4F7F\u7528 Ctrl+S \u4FDD\u5B58\u6587\u4EF6\uFF0C\u517B\u6210\u597D\u4E60\u60EF\u3002',c:'\u7F16\u7A0B\u6280\u5DE7'},{t:'Git \u7684 rebase -i \u53EF\u4EE5\u6574\u7406\u63D0\u4EA4\u5386\u53F2\u3002',c:'Git \u6280\u5DE7'},{t:'\u5728\u7EC8\u7AEF\u4E2D\u4F7F\u7528 * \u901A\u914D\u7B26\u53EF\u4EE5\u5339\u914D\u591A\u4E2A\u6587\u4EF6\u3002',c:'Linux \u6280\u5DE7'},{t:'Arch Linux \u7684 pacman -Syu \u662F\u7CFB\u7EDF\u66F4\u65B0\u547D\u4EE4\u3002',c:'Arch Linux'},{t:'\u4F7F\u7528 ChatGPT \u5199\u4EE3\u7801\u65F6\uFF0C\u63D0\u4F9B\u4E0A\u4E0B\u6587\u80FD\u83B7\u5F97\u66F4\u597D\u7684\u7B54\u6848\u3002',c:'AI \u5DE5\u5177'},{t:'CSS Grid \u6BD4 Flexbox \u66F4\u9002\u5408\u4E8C\u7EF4\u5E03\u5C40\u3002',c:'\u7F16\u7A0B\u6280\u5DE7'},{t:'\u4F7F\u7528 tmux \u53EF\u4EE5\u7BA1\u7406\u7EC8\u7AEF\u4F1A\u8BDD\u3002',c:'Linux \u6280\u5DE7'},{t:'yay \u662F Arch Linux \u4E0A\u5E38\u7528\u7684 AUR \u52A9\u624B\u3002',c:'Arch Linux'}],async init(){this.render();document.getElementById('refresh-inspiration')?.addEventListener('click',()=>this.render())},render(){const p=this.tips[Math.floor(Math.random()*this.tips.length)];const c=document.getElementById('inspiration-category'),t=document.getElementById('inspiration-text');if(c)c.textContent=p.c;if(t)t.textContent=p.t}};

/* ====== Settings ====== */const Settings={init(){const s=Storage.get('settings',{theme:'auto',color:'purple',fs:14});if(s.theme==='light')document.documentElement.setAttribute('data-theme','light');else if(s.theme==='dark')document.documentElement.removeAttribute('data-theme');else{if(window.matchMedia('(prefers-color-scheme:light)').matches)document.documentElement.setAttribute('data-theme','light')}this.color(s.color);document.body.style.fontSize=s.fs+'px';document.querySelector(`input[name="theme"][value="${s.theme}"]`)?.setAttribute('checked','');document.querySelectorAll('.swatch').forEach(s=>{s.classList.toggle('active',s.dataset.color===s.color)});const sl=document.getElementById('font-size-slider');if(sl)sl.value=s.fs;document.getElementById('settings-btn')?.addEventListener('click',()=>document.getElementById('settings-overlay').classList.add('active'));document.getElementById('close-settings')?.addEventListener('click',()=>document.getElementById('settings-overlay').classList.remove('active'));document.getElementById('settings-overlay')?.addEventListener('click',e=>{if(e.target===e.target)e.target.classList.remove('active')});document.querySelectorAll('input[name="theme"]').forEach(r=>{r.addEventListener('change',e=>{const s=Storage.get('settings',{});s.theme=e.target.value;Storage.set('settings',s);if(e.target.value==='light')document.documentElement.setAttribute('data-theme','light');else if(e.target.value==='dark')document.documentElement.removeAttribute('data-theme');else{if(window.matchMedia('(prefers-color-scheme:light)').matches)document.documentElement.setAttribute('data-theme','light')}})});document.querySelectorAll('.swatch').forEach(sw=>{sw.addEventListener('click',()=>{document.querySelectorAll('.swatch').forEach(s=>s.classList.remove('active'));sw.classList.add('active');this.color(sw.dataset.color);const s=Storage.get('settings',{});s.color=sw.dataset.color;Storage.set('settings',s)})});document.getElementById('font-size-slider')?.addEventListener('input',e=>{const s=+e.target.value;document.body.style.fontSize=s+'px';const st=Storage.get('settings',{});st.fs=s;Storage.set('settings',st)})},color(c){const colors={purple:{s:'#a78bfa',e:'#60a5fa'},blue:{s:'#60a5fa',e:'#3b82f6'},green:{s:'#34d399',e:'#10b981'},orange:{s:'#fbbf24',e:'#f59e0b'},pink:{s:'#f472b6',e:'#ec4899'}};const co=colors[c]||colors.purple;document.documentElement.style.setProperty('--accent-start',co.s);document.documentElement.style.setProperty('--accent-end',co.e)}};

/* ====== Charts ====== */let charts={};
function getHist(key,range){const n=new Date(),labels=[],data=[];const days=range==='month'?30:7;for(let i=days-1;i>=0;i--){const d=new Date(n);d.setDate(d.getDate()-i);labels.push(`${d.getMonth()+1}/${d.getDate()}`);data.push(Storage.get(`${key}_${U.getToday()}`,0))}return{labels,data}}
function initChart(id,conf){const c=document.getElementById(id);if(!c)return null;if(charts[id])charts[id].destroy();charts[id]=new Chart(c.getContext('2d'),conf);return charts[id]}
function chartColors(){const s=getComputedStyle(document.documentElement);return{text:s.getPropertyValue('--text-secondary').trim()||'#8a8f96',start:s.getPropertyValue('--accent-start').trim()||'#a78bfa',grid:s.getPropertyValue('--border-color').trim()||'rgba(255,255,255,0.08)'}}
function updateCharts(){updWater();updFocus();updSleep();updTodo()}
function updWater(){const{labels,data}=getHist('water','week');const co=chartColors();initChart('water-chart',{type:'line',data:{labels,datasets:[{label:'\u996E\u6C34\u91CF (ML)',data,backgroundColor:co.start+'22',borderColor:co.start,tension:0.4,fill:true}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:co.text},grid:{color:co.grid}},y:{ticks:{color:co.text},grid:{color:co.grid}}}}})}
function updFocus(){const{labels,data}=getHist('focus','week');const co=chartColors();initChart('focus-chart',{type:'bar',data:{labels,datasets:[{label:'\u4E13\u6CE8\u65F6\u957F (min)',data,backgroundColor:co.start+'88',borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:co.text},grid:{color:co.grid}},y:{ticks:{color:co.text},grid:{color:co.grid}}}}})}
function updSleep(){const{labels,data}=getHist('sleep','week');const co=chartColors();initChart('sleep-chart',{type:'line',data:{labels,datasets:[{label:'\u7761\u7720\u65F6\u957F (min)',data,backgroundColor:co.start+'22',borderColor:co.start,tension:0.4,fill:true}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:co.text},grid:{color:co.grid}},y:{ticks:{color:co.text},grid:{color:co.grid}}}}})}
function updTodo(){const n=new Date(),labels=[],data=[];for(let i=6;i>=0;i--){const d=new Date(n);d.setDate(d.getDate()-i);labels.push(`${d.getMonth()+1}/${d.getDate()}`);const todos=Storage.get('todos',[]),dt=d.toISOString().slice(0,10);const dayT=todos.filter(t=>t.date===dt);const done=dayT.filter(t=>t.done).length;data.push(dayT.length?Math.round((done/dayT.length)*100):0)}const co=chartColors();initChart('todo-chart',{type:'bar',data:{labels,datasets:[{label:'\u5B8C\u6210\u7387 (%)',data,backgroundColor:data.map(v=>v>=80?co.start+'88':v>=50?'#fbbf2488':'#f8717188'),borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:co.text},grid:{color:co.grid}},y:{max:100,ticks:{color:co.text},grid:{color:co.grid}}}}})}

/* ====== Theme Toggle ====== */
document.getElementById('theme-toggle')?.addEventListener('click',()=>{const c=document.documentElement.getAttribute('data-theme');if(c==='light')document.documentElement.setAttribute('data-theme','dark');else document.documentElement.removeAttribute('data-theme');const s=Storage.get('settings',{});s.theme=c==='light'?'dark':'light';Storage.set('settings',s)});

/* ====== Sidebar Toggle ====== */
document.getElementById('sidebar-toggle')?.addEventListener('click',()=>{document.getElementById('sidebar').classList.toggle('collapsed')});
document.getElementById('mobile-menu-btn')?.addEventListener('click',()=>{document.getElementById('sidebar').classList.toggle('mobile-open')});

/* ====== Init ====== */
document.addEventListener('DOMContentLoaded',()=>{
  Clock.init();
  Weather.init();
  Quotes.init();
  Todo.init();
  Todo.initInput('todo-input','add-todo');
  Todo.initInput('todo-input-2','add-todo-2');
  Stats.init();
  Pomo.init();
  Notes.init();
  Calendar.init();
  Insp.init();
  Settings.init();
  Router.init();
  document.querySelectorAll('.toggle-btn').forEach(b=>{b.addEventListener('click',()=>{b.parentElement.querySelectorAll('.toggle-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');updateCharts()})});
  if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();
});